# Generated by Django 6.0.6 on 2026-06-23 08:10

import api_controller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api_controller.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
